package main

import (
	"log"
	"net/http"
	"strings"

	_ "orchestrator/internal/api/docs" // generated by swag init
	"orchestrator/internal/store"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

type createGroupRequest struct {
	Name string `json:"name"`
}

func main() {
	r := gin.Default()

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.POST("/groups", func(c *gin.Context) {
		var req createGroupRequest
		if err := c.ShouldBindJSON(&req); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid JSON body"})
			return
		}

		name := strings.TrimSpace(req.Name)
		if name == "" {
			c.JSON(http.StatusBadRequest, gin.H{"error": "name is required"})
			return
		}

		if _, exists := store.GetGroup(name); exists {
			c.JSON(http.StatusConflict, gin.H{"error": "group already exists"})
			return
		}

		g := store.CreateGroup(name)
		c.JSON(http.StatusCreated, g)
	})

	r.GET("/groups", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"groups": store.ListGroups()})
	})

	r.GET("/groups/:name", func(c *gin.Context) {
		name := c.Param("name")
		g, ok := store.GetGroup(name)
		if !ok {
			c.JSON(http.StatusNotFound, gin.H{"error": "group not found"})
			return
		}
		c.JSON(http.StatusOK, g)
	})

	if err := r.Run(); err != nil {
		log.Fatalf("failed to run server: %v", err)
	}
}
